name: Run unit tests

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Unit tests
      run: bash ./gradlew testPurefossDebug -PdisablePreDex --no-daemon
    - name: Archive test results
      uses: actions/upload-artifact@v1
      with:
        name: test-results
        path: app/build/test-results/testPurefossDebugUnitTest/
    - name: Archive test reports
      uses: actions/upload-artifact@v1
      with:
        name: test-reports
        path: app/build/reports/tests
